services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - /opt/jellyfish/config:/config
      - /opt/jellyfish/cache:/cache
      - type: bind
        source: /opt/jellyfish/media
        target: /media
        read_only: true
    restart: 'unless-stopped'
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'