! ----------------
! ROFI Color theme
! User: neurotech
! ----------------

rofi.color-enabled: true

!                  bg       border   separator
rofi.color-window: #666699, #292a44, #383a62

!                  bg       fg       bg-alt   hl-bg    hl-fg
rofi.color-normal: #666699, #f1eff8, #666699, #efe4a1, #53495d
rofi.color-active: #2de0a7, #666699, #2de0a7, #2de0a7, #666699
rofi.color-urgent: #ff79c6, #666699, #ff79c6, #ff79c6, #666699